
import Footer from './common/footer'
import Navbar from './common/navbar'
import { DineMarketContextProvider } from './context/DineMarketContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <DineMarketContextProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </DineMarketContextProvider>
      </body>

    </html>
  )
}
